name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore HelloWorldTool/HelloWorldTool.csproj
    
    - name: Build
      run: dotnet build HelloWorldTool/HelloWorldTool.csproj --no-restore --configuration Release
    
    - name: Test
      run: dotnet test HelloWorldTool/HelloWorldTool.csproj --no-build --configuration Release --verbosity normal
    
    - name: Pack
      run: dotnet pack HelloWorldTool/HelloWorldTool.csproj --no-build --configuration Release --output ./packages
    
    - name: Publish to GitHub Packages
      run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
