name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore HelloWorldTool/HelloWorldTool.csproj
    
    - name: Build
      run: dotnet build HelloWorldTool/HelloWorldTool.csproj --no-restore --configuration Release
    
    - name: Pack
      run: dotnet pack HelloWorldTool/HelloWorldTool.csproj --no-build --configuration Release --output ./packages
    
    - name: List packages
      run: ls -la ./packages/
    
    - name: Publish to GitHub Packages
      run: |
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet nuget push ./packages/*.nupkg --source github --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
